FROM node:20-alpine
WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
COPY packages/eslint-config/package.json packages/eslint-config/
COPY packages/shared/package.json packages/shared/
COPY packages/tsconfig/package.json packages/tsconfig/
COPY apps/admin/package*.json apps/admin/

RUN npm install

COPY apps/admin/ apps/admin/

WORKDIR /app/apps/admin

EXPOSE 3000

CMD ["npm", "run", "dev"]
